In [1]:
# https://pandas.pydata.org/docs/user_guide/10min.html
import pandas as pd
import numpy as np

In [15]:
# create a series & dataframe
s = pd.Series([1,2,3,np.nan,5])
print(s)
df=pd.DataFrame(np.random.randn(3,4))
print(df)

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64
          0         1         2         3
0 -0.394776  0.505273 -0.510942  0.428670
1 -1.459781  0.220112 -0.822460  0.303192
2  0.535120  0.378329  0.612874 -1.658803

In [37]:
# DF properties & viewing data
df2 = pd.DataFrame({
    "A" :1.0,
    "B" :pd.Timestamp("20130201"),
    "C" :pd.Series(1, index=list(range(4)), dtype="float32"),
    "D" :np.array([3]*4, dtype="int32"),
    "E" :pd.Categorical(["test", "train", "test", "train"]),
    "F" :"col",
})
print(df2)
print("\n")
print("*"*30)
print("DF2 Datatypes")
print("*"*30)
print(df2.dtypes)
print("\n")
print("*"*30)
print("DF2 first 2 rows")
print("*"*30)
print(df2.head(2))
print("\n")
print("*"*30)
print("DF2 last 2 rows")
print("*"*30)
print(df2.tail(2))
print("\n")
print("*"*30)
print("DF2 Index")
print("*"*30)
print(df2.index)
print("\n")
print("*"*30)
print("DF2 column names")
print("*"*30)
print(df2.columns)
print("\n")
print("*"*30)
print("DF2 describe")
print("*"*30)
print(df2.describe())
print("\n")
print("*"*30)
print("DF2 Sort by Index and Values")
print("*"*30)
print(df2.sort_index(axis=1,ascending=False))
print(df2.sort_values(by="E"))

     A          B    C  D      E    F
0  1.0 2013-02-01  1.0  3   test  col
1  1.0 2013-02-01  1.0  3  train  col
2  1.0 2013-02-01  1.0  3   test  col
3  1.0 2013-02-01  1.0  3  train  col


******************************
DF2 Datatypes
******************************
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


******************************
DF2 first 2 rows
******************************
     A          B    C  D      E    F
0  1.0 2013-02-01  1.0  3   test  col
1  1.0 2013-02-01  1.0  3  train  col


******************************
DF2 last 2 rows
******************************
     A          B    C  D      E    F
2  1.0 2013-02-01  1.0  3   test  col
3  1.0 2013-02-01  1.0  3  train  col


******************************
DF2 Index
******************************
Int64Index([0, 1, 2, 3], dtype='int64')


******************************
DF2 column names
******************************
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


******************************
DF2 describe
******************************
         A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0


******************************
DF2 Sort by Index and Values
******************************
     F      E  D    C          B    A
0  col   test  3  1.0 2013-02-01  1.0
1  col  train  3  1.0 2013-02-01  1.0
2  col   test  3  1.0 2013-02-01  1.0
3  col  train  3  1.0 2013-02-01  1.0
     A          B    C  D      E    F
0  1.0 2013-02-01  1.0  3   test  col
2  1.0 2013-02-01  1.0  3   test  col
1  1.0 2013-02-01  1.0  3  train  col
3  1.0 2013-02-01  1.0  3  train  col

In [65]:
# Selection
df2=pd.DataFrame({
    "AB" : pd.date_range("20220301", periods=5),
    "BC" : pd.Series(list(range(5))),
    "CD" : pd.Categorical(['Shxxx','Hmxxx','Jixxx','Smxxx','Lmxxx'])
})
# df2 = df2.set_index("AB")
print(df2)
print("\n")
print("*"*30)
print(df2.BC) # Equivalent to df2['BC']
print("\n")
print("*"*30)
print(df2[2:4])
# Selection by label
print("\n")
print("*"*30)
print(df2.loc[:,['BC']])

          AB  BC     CD
0 2022-03-01   0  Shxxx
1 2022-03-02   1  Hmxxx
2 2022-03-03   2  Jixxx
3 2022-03-04   3  Smxxx
4 2022-03-05   4  Lmxxx


******************************
0    0
1    1
2    2
3    3
4    4
Name: BC, dtype: int64


******************************
          AB  BC     CD
2 2022-03-03   2  Jixxx
3 2022-03-04   3  Smxxx


******************************
   BC
0   0
1   1
2   2
3   3
4   4